### ISSUE TITLE
Can ecs-exporter work running as a task in ECS using a Task Role IAM policy?

### ISSUE THREAD

**Issue by david-kli** [slok/ecs-exporter#1]
I am trying to run ecs-exporter in a ECS cluster and attached a IAM policy to the task allowing specific permissions.  I have ecs:ListClusters granted in the policy, but I get an assumed-role X is not authorized to perform: ecs:ListClusters on resource: * error in the ecs-exporter docker logs.

I have tried adjusting the iam policy to ecs:* and still get the same error.  I can run the docker container locally using my admin AWS key without issue.

Here is the IAM policy I am attaching to the task (The iam policy does allow for ecs-tasks.amazonaws.com to assume the role):
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Action": [
        "ecs:Poll",
        "ecs:ListTasks",
        "ecs:ListContainerInstances",
        "ecs:ListClusters",
        "ecs:DescribeTasks",
        "ecs:DescribeContainerInstances",
        "ecs:DescribeClusters",
        "ec2:DescribeInstances"
      ],
      "Resource": "*"
    }
  ]
}

I appreciate any help and insights you can provide,
David

**Comment by slok** [comment]
Hi! 

Strange! It seems that the ecs task is not getting the role correctly. Do you have any other tasks using roles? Also as a test you could let the task take ECS instance role and set that policy in the instance role.

**Comment by david-kli** [comment]
You are absolutely correct!  I was missing a small but critical piece of actually associating the IAM policy to the task.  After the correction, ecs-exporter is working like a champ.

Apologies for the non-issue and thank you for your fast response.
