### ISSUE TITLE
Question: How often are the ECS APIs queired?

### ISSUE THREAD

**Issue by knspriggs** [slok/ecs-exporter#9]
How often are the ECS APIs queried? I noticed that there is no configuration value for the "scrape interval".

**Comment by knspriggs** [comment]
I see now that the scrape occurs when prometheus hits the `/metrics` endpoint.

**Comment by slok** [comment]
That's right!

When Prometheus hits the endpoint it scrapes and returns the new metrics.

More info here: https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling :)

Best!

**Comment by knspriggs** [comment]
I feel like the answer only ever appears after I ask a stupid question! :) Thanks again!
